### ISSUE TITLE
Crash during members update if member lastknowlocation cannot be found

### ISSUE THREAD

**Issue by tialhungen** [evecm/ecm#10]
during the member list upgrade, my ECM crashed with the following error message :
```sh
2014-12-31 16:38:01,123 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/xxx/ecm-instance/venv/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "xxx/ecm-instance/venv/lib/python2.7/site-packages/ecm/apps/hr/tasks/users.py", line 42, in update_all_character_associations
    update_character_associations(user)
  File "xxx/ecm-instance/venv/lib/python2.7/site-packages/ecm/apps/hr/tasks/users.py", line 66, in update_character_associations
    set_char_info_attributes(member, char_info)
  File "xxx/ecm-instance/venv/lib/python2.7/site-packages/ecm/apps/hr/tasks/charactersheet.py", line 91, in set_char_info_attributes
    member.location = char_info.lastKnownLocation
AttributeError: 'Element' object has no attribute 'lastKnownLocation'
```

**Comment by tialhungen** [comment]
Proposed patch

``` diff
f916b4ef67b1077325eda9514845b00c781643f8 Avoid crash in member update in case of empty lastknowlocation and shipname.
diff --git a/ecm/apps/hr/tasks/charactersheet.py b/ecm/apps/hr/tasks/charactersheet.py
index 38547f3..85f4055 100644
--- a/ecm/apps/hr/tasks/charactersheet.py
+++ b/ecm/apps/hr/tasks/charactersheet.py
@@ -94,8 +94,14 @@
 
 #-----------------------------------------------------------------------------
 def set_char_info_attributes(member, char_info):
-    member.location = char_info.lastKnownLocation
-    member.ship = char_info.shipTypeName
+    try:
+        member.location = char_info.lastKnownLocation
+    except AttributeError:
+        member.location = None
+    try:
+        member.ship = char_info.shipTypeName
+    except AttributeError:
+        member.ship = None
     history = member.employment_history.values_list('recordID', flat=True)
     for employer in char_info.employmentHistory:
         if employer.recordID not in history:
```

**Comment by ggrog** [comment]
Thanks, I'll add in the patch.
