### ISSUE TITLE
Error when running scheduled tasks

### ISSUE THREAD

**Issue by tyler274** [evecm/ecm#11]
When running these they fail
ecm.plugins.accounting.tasks.contracts.update
ecm.plugins.accounting.tasks.wallets.update

[ERROR] django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/middleware/locale.py", line 21, in process_request
    check_path = self.is_language_prefix_patterns_used()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/middleware/locale.py", line 56, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/urls.py", line 26, in <module>
    from ecm.views.account.forms import PasswordChangeForm, PasswordResetForm, PasswordSetForm
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/views/__init__.py", line 151, in <module>
    create_app_objects(app)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/views/__init__.py", line 129, in create_app_objects
    directors = get_directors_group()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/common/auth.py", line 36, in get_directors_group
    return get_or_create_group(Setting.get('hr_directors_group_name'))
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/common/models.py", line 64, in get
    return Setting.objects.get(name=name).getValue()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: Setting matching query does not exist.

**Comment by tyler274** [comment]
Im sorry, it was late....

**Comment by ggrog** [comment]
What was the issue?

**Comment by tyler274** [comment]
I was actually going to reopen this because what i thought it was turned our not to be the cause.

**Comment by tyler274** [comment]
Any ideas what the error could be?

**Comment by ggrog** [comment]
Yes.  The key line here that's failing is:
return get_or_create_group(Setting.get('hr_directors_group_name'))

If it can't get that setting, it's because the init is failing.  The one time I've seen this is because of an invalid email address in either the Apache config (please set ServerAdmin to something real) or when you did ecm-admin create.

You can verify this is the issue by turning on debugging by setting Debug=true in settings.ini and reloading your site page.  Look at the variable list to see if there's a email address that doesn't make sense.

**Comment by tyler274** [comment]
The bug seems to have gone away, but i don't use apache (nginx). I checked the email in the settings.ini though and updated the email so I'm going to say that probably fixed it, though I am not sure.
