### ISSUE TITLE
Integrity error on blueprint import

### ISSUE THREAD

**Issue by tyler274** [evecm/ecm#15]
Traceback:
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  115.                         response = callback(request, *callback_args, **callback_kwargs)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/transaction.py" in inner
  223.                 return func(*args, **kwargs)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/views/decorators.py" in _wrapped_view
  104.                     return view_function(request, *args, **kwargs)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/plugins/industry/views/catalog/import_blueprints.py" in blueprints
  67.                                                                 is_available=False)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/manager.py" in create
  149.         return self.get_query_set().create(**kwargs)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py" in create
  416.         obj.save(force_insert=True, using=self.db)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/base.py" in save
  546.                        force_update=force_update, update_fields=update_fields)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/base.py" in save_base
  650.                 result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/manager.py" in _insert
  215.         return insert_query(self.model, objs, fields, **kwargs)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py" in insert_query
  1675.     return query.get_compiler(using=using).execute_sql(return_id)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  943.             cursor.execute(sql, params)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/backends/util.py" in execute
  41.             return self.cursor.execute(sql, params)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py" in execute
  127.                 six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py" in execute
  120.             return self.cursor.execute(query, args)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/home/bovril/ecm2/local/lib/python2.7/site-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: IntegrityError at /industry/catalog/blueprints/import/
Exception Value: (1048, "Column 'typeID' cannot be null")

**Comment by ggrog** [comment]
Turns out my proteus DB dumps are missing blueprint data, which I believe is causing this error.  I am working on the fuzzworks conversion scripts now.  Stay tuned.

**Comment by tyler274** [comment]
Awesome, thanks once again for keeping this project updated.

**Comment by ggrog** [comment]
OK, I've added the ability to load static data from Fuzzwork if you're using mysql/mariadb.  Any interest in trying it out, and seeing if it fixes this error?

Run:
pip install git+https://github.com/evecm/ecm.git
ecm-admin upgrade /your/instance
ecm-admin load /your/instance --fuzzwork

**Comment by tyler274** [comment]
I just got back from a trip (no internet), pulling changes now.

**Comment by tyler274** [comment]
did the steps as advised, ran the tasks ( I am still getting the member and related tasks 'id' error) but the import blueprint option still spits out this traceback 

2015-01-26 18:36:23,775 [ERROR] django.request - Internal Server Error: /industry/catalog/blueprints/import/data/
Traceback (most recent call last):
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/views/decorators.py", line 104, in _wrapped_view
    return view_function(request, *args, **kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/plugins/industry/views/catalog/import_blueprints.py", line 110, in blueprints_data
    location_name = celestial_objects.get(itemID=bp.closest_object_id).itemName
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: CelestialObject matching query does not exist.

**Comment by ggrog** [comment]
Try updating the corp assets (may take several minutes), and then retrying the import blueprints option.

**Comment by tyler274** [comment]
Some blueprints imported but this error still comes up, and the site fails to load "All Blueprints" and "Only Copies" 

2015-01-26 22:00:31,361 [ERROR] django.request - Internal Server Error: /industry/catalog/blueprints/import/data/
Traceback (most recent call last):
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/views/decorators.py", line 104, in _wrapped_view
    return view_function(request, *args, **kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/plugins/industry/views/catalog/import_blueprints.py", line 110, in blueprints_data
    location_name = celestial_objects.get(itemID=bp.closest_object_id).itemName
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: CelestialObject matching query does not exist.

**Comment by ggrog** [comment]
Closing, pending actual blueprint system rework in #39
