### ISSUE TITLE
Outstanding Contracts

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#20]
I noticed that fulfiled, finished contracts are still shown as outstanding.

Any idea why? I use release 2.2.2b and have no other issues besides this.

**Comment by ggrog** [comment]
Are you seeing relevant errors or information in the log files?  /instancedir/logs/ecm.log and error.log.

**Comment by Dharr-Guartonzec** [comment]
Error Log contains nothing at all, and here is the ecm.log filtered to "c/Contracts":

# cat ecm.log | grep 'ontracts'
2015-06-01 03:10:04,850 [INFO ] ecm.plugins.accounting.tasks.contracts - fetching /corp/Contracts.xml.aspx...
2015-06-01 03:10:05,287 [INFO ] ecm.plugins.accounting.tasks.contracts - 8 old contracts removed.
2015-06-01 03:10:05,289 [INFO ] ecm.plugins.accounting.tasks.contracts - 1 new contracts added.
2015-06-01 03:10:05,296 [INFO ] ecm.plugins.accounting.tasks.contracts - 8 old contract items removed.
2015-06-01 03:10:05,303 [INFO ] ecm.plugins.accounting.tasks.contracts - 18 new contract items added.
2015-06-01 09:15:04,259 [INFO ] ecm.plugins.accounting.tasks.contracts - fetching /corp/Contracts.xml.aspx...
2015-06-01 09:15:04,670 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 old contracts removed.
2015-06-01 09:15:04,673 [INFO ] ecm.plugins.accounting.tasks.contracts - 1 new contracts added.
2015-06-01 09:15:04,674 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 new contract items added.
2015-06-01 15:20:04,131 [INFO ] ecm.plugins.accounting.tasks.contracts - fetching /corp/Contracts.xml.aspx...
2015-06-01 15:20:04,424 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 old contracts removed.
2015-06-01 15:20:04,424 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 new contracts added.
2015-06-01 15:20:04,424 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 new contract items added.
#

So i don't see any errors. Today 18 new contracts is not correct, we just have only one new contract atm. In total ECM reports me currently 67 outstanding contracts, but only one currently is outstanding - all others are completed.

What else could i provide to help here? Unfortunately in things of coding i'm a bloody noob.

**Comment by ggrog** [comment]
The debug log could be useful.  First, in your settings.ini, set Debug=True.  Then restart your instance, and force a contract update from the Scheduled Tasks page.  (ecm.plugins.accounting.tasks.contracts.update)  The debug output does not go to ecm.log, it goes to stderr.  If you're running your instance from the command line, you should just see the debug output there.  If you're using mod_wsgi or something similar the output is likely in your main apache log, for me that's /var/log/apache2/error.log.

**Comment by Dharr-Guartonzec** [comment]
Okay, here we go. there seems to be an issue with the ECM error.log. Apache error.log reports that it can't access the error.log in the ECM path. Normal logs work fine. So i gave it a CHMOD 777 but that did not help, and even after i deleted it - it is not recreated but in Apache's error.log still it says can't access it. Here is the output after enabling DEBUG in settings.ini:

[Mon Jun 01 20:14:44.875644 2015] [mpm_prefork:notice] [pid 30104] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Mon Jun 01 20:14:44.875762 2015] [core:notice] [pid 30104] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Jun 01 20:14:49.095161 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152] mod_wsgi (pid=30105): Exception occurred processing WSGI script '/var/www/ecm/wsgi/ecm.wsgi'.
[Mon Jun 01 20:14:49.095292 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152] Traceback (most recent call last):
[Mon Jun 01 20:14:49.095315 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
[Mon Jun 01 20:14:49.095558 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     self.load_middleware()
[Mon Jun 01 20:14:49.095573 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
[Mon Jun 01 20:14:49.095757 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Mon Jun 01 20:14:49.095769 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
[Mon Jun 01 20:14:49.095896 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     self._setup(name)
[Mon Jun 01 20:14:49.095907 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
[Mon Jun 01 20:14:49.095925 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     self._configure_logging()
[Mon Jun 01 20:14:49.095935 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 84, in _configure_logging
[Mon Jun 01 20:14:49.095950 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     logging_config_func(self.LOGGING)
[Mon Jun 01 20:14:49.095959 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib64/python2.7/logging/config.py", line 803, in dictConfig
[Mon Jun 01 20:14:49.096334 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     dictConfigClass(config).configure()
[Mon Jun 01 20:14:49.096364 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]   File "/usr/lib64/python2.7/logging/config.py", line 585, in configure
[Mon Jun 01 20:14:49.096596 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152]     '%r: %s' % (name, e))
[Mon Jun 01 20:14:49.096619 2015] [:error] [pid 30105] [remote xxx.xxx.xxx.xxx:152] ValueError: Unable to configure handler 'error_file_handler': [Errno 13] Permission denied: '/var/www/ecm/logs/error.log'
[Mon Jun 01 20:14:54.011804 2015] [:error] [pid 30105] /usr/lib/python2.7/site-packages/django/utils/hashcompat.py:9: DeprecationWarning: django.utils.hashcompat is deprecated; use hashlib instead
[Mon Jun 01 20:14:54.011848 2015] [:error] [pid 30105]   DeprecationWarning)
[Mon Jun 01 20:14:54.011851 2015] [:error] [pid 30105]

**Comment by ggrog** [comment]
Make sure to open access to the entire log directory; chmod -R 777 /var/www/ecm

(Obligatory "use chmod 777 with caution!" warning)

**Comment by Dharr-Guartonzec** [comment]
I did that on the whole logs directory, now the error.log got created but is still empty while apache still reports that it has no access to that file.

# ls -la
total 744
drwxrwxrwx. 2 apache root    4096 Jun  1 20:15 .
drwxr-xr-x. 7 apache root    4096 Jun  1 20:06 ..
-rwxrwxrwx. 1 apache apache 67169 Jun  1 20:35 ecm.log
-rwxrwxrwx. 1 apache apache 49404 May 17 22:25 ecm.log.2015-05-17
-rwxrwxrwx. 1 apache apache 42785 May 18 23:15 ecm.log.2015-05-18
-rwxrwxrwx. 1 apache apache 40184 May 19 23:05 ecm.log.2015-05-19
-rwxrwxrwx. 1 apache apache 40334 May 20 23:25 ecm.log.2015-05-20
-rwxrwxrwx. 1 apache apache 43409 May 21 23:45 ecm.log.2015-05-21
-rwxrwxrwx. 1 apache apache 44444 May 22 23:05 ecm.log.2015-05-22
-rwxrwxrwx. 1 apache apache 43708 May 23 22:00 ecm.log.2015-05-23
-rwxrwxrwx. 1 apache apache 45796 May 24 23:00 ecm.log.2015-05-24
-rwxrwxrwx. 1 apache apache 43489 May 25 21:55 ecm.log.2015-05-25
-rwxrwxrwx. 1 apache apache 44846 May 26 22:55 ecm.log.2015-05-26
-rwxrwxrwx. 1 apache apache 47628 May 27 23:55 ecm.log.2015-05-27
-rwxrwxrwx. 1 apache apache 43633 May 28 22:50 ecm.log.2015-05-28
-rwxrwxrwx. 1 apache apache 41950 May 29 23:50 ecm.log.2015-05-29
-rwxrwxrwx. 1 apache apache 42753 May 30 22:45 ecm.log.2015-05-30
-rwxrwxrwx. 1 apache apache 43319 May 31 23:45 ecm.log.2015-05-31
-rwxrwxrwx. 1 apache apache     0 Jun  1 20:15 error.log
#

User and group seems correct.

**Comment by ggrog** [comment]
It certainly looks like it should work.  You're sure the file isn't open elsewhere, or there's not multiple apache instances running?

To work around just to see the debug messages, you can use the Django built in webserver ```sudo /var/www/ecm/manage.py runserver 0.0.0.0:12345``` and connect to your site at the alternate port.  You'll see the debug messages at the console.

And connec

**Comment by Dharr-Guartonzec** [comment]
tbh - unsure if some instance is blocking i go kill them all. but here for example is the 12345 test instance output:

# /var/www/ecm/manage.py runserver 0.0.0.0:12345
Validating models...

0 errors found
June 01, 2015 - 22:41:09
Django version 1.5.7, using settings 'settings'
Development server is running at http://0.0.0.0:12345/
Quit the server with CONTROL-C.
2015-06-01 22:41:27,840 [INFO ] ecm.plugins.industry.views - Initialized item groups (took 0.39 sec.)
[01/Jun/2015 22:41:27] "GET / HTTP/1.1" 302 0
[01/Jun/2015 22:41:28] "GET /corp/ HTTP/1.1" 200 11130
[01/Jun/2015 22:41:28] "GET /static/ecm/css/dataTables.bootstrap.css HTTP/1.1" 200 2306
[01/Jun/2015 22:41:28] "GET /static/ecm/css/bootstrap-responsive.css HTTP/1.1" 200 14447
[01/Jun/2015 22:41:28] "GET /static/ecm/css/jquery.cluetip.css HTTP/1.1" 200 4688
[01/Jun/2015 22:41:28] "GET /static/ecm/css/classes.css HTTP/1.1" 200 198
[01/Jun/2015 22:41:28] "GET /static/ecm/css/bootstrap-ecm.css HTTP/1.1" 200 2178
[01/Jun/2015 22:41:28] "GET /static/ecm/css/bootstrap.css HTTP/1.1" 200 99896
[01/Jun/2015 22:41:28] "GET /static/ecm/js/csrf.js HTTP/1.1" 200 1029
[01/Jun/2015 22:41:28] "GET /static/ecm/js/ecm_lib.js HTTP/1.1" 200 5736
[01/Jun/2015 22:41:28] "GET /static/ecm/js/bootstrap.js HTTP/1.1" 200 50108
[01/Jun/2015 22:41:28] "GET /static/ecm/js/lib/jquery.jeditable.js HTTP/1.1" 200 22796
[01/Jun/2015 22:41:28] "GET /static/ecm/js/lib/jquery.json.js HTTP/1.1" 200 4712
[01/Jun/2015 22:41:28] "GET /static/ecm/js/lib/jquery.js HTTP/1.1" 200 248235
[01/Jun/2015 22:41:28] "GET /static/ecm/js/jquery.datatables.saveascsv.js HTTP/1.1" 200 3564
[01/Jun/2015 22:41:28] "GET /static/ecm/js/lib/jquery.dataTables.js HTTP/1.1" 200 361238
[01/Jun/2015 22:41:28] "GET /static/ecm/js/dataTables.bootstrap.js HTTP/1.1" 200 3397
[01/Jun/2015 22:41:28] "GET /static/ecm/img/logo.png HTTP/1.1" 200 3763
[01/Jun/2015 22:41:28] "GET /static/ecm/js/lib/jquery.cluetip.js HTTP/1.1" 200 23949
[01/Jun/2015 22:41:28] "GET /static/ecm/img/glyphicons-halflings-white.png HTTP/1.1" 200 8777
[01/Jun/2015 22:41:29] "GET /static/ecm/img/favicon.ico HTTP/1.1" 200 364726
[01/Jun/2015 22:41:32] "GET /scheduler/tasks/ HTTP/1.1" 200 12273
[01/Jun/2015 22:41:32] "GET /scheduler/tasks/data/?sEcho=1&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191321692 HTTP/1.1" 200 3534
[01/Jun/2015 22:41:37] "GET /scheduler/tasks/data/?sEcho=2&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191326702 HTTP/1.1" 200 3534
[01/Jun/2015 22:41:41] "GET /scheduler/tasks/13/launch/ HTTP/1.1" 202 0
2015-06-01 22:41:41,052 [INFO ] ecm.plugins.accounting.tasks.contracts - fetching /corp/Contracts.xml.aspx...
2015-06-01 22:41:41,055 [DEBUG] ecm.plugins.accounting.tasks.contracts - Fetching Contracts...
[01/Jun/2015 22:41:41] "GET /static/ecm/img/clock.png HTTP/1.1" 200 965
2015-06-01 22:41:41,290 [DEBUG] ecm.plugins.accounting.tasks.contracts - current time : 2015-06-01 20:42:07+00:00
2015-06-01 22:41:41,290 [DEBUG] ecm.plugins.accounting.tasks.contracts - cached util : 2015-06-01 20:56:07+00:00
2015-06-01 22:41:41,290 [DEBUG] ecm.plugins.accounting.tasks.contracts - parsing api response...
2015-06-01 22:41:41,294 [DEBUG] ecm.plugins.accounting.tasks.contracts - Fetching contracts from DB...
2015-06-01 22:41:41,307 [DEBUG] ecm.plugins.accounting.tasks.contracts - 93 contracts found in DB...
2015-06-01 22:41:41,307 [DEBUG] ecm.plugins.accounting.tasks.contracts - Fetching contracts from API...
2015-06-01 22:41:41,325 [DEBUG] ecm.plugins.accounting.tasks.contracts - Contracts from API: 93
2015-06-01 22:41:41,326 [DEBUG] ecm.plugins.accounting.tasks.contracts - Removed contracts: 0
2015-06-01 22:41:41,326 [DEBUG] ecm.plugins.accounting.tasks.contracts - Added contracts: 0
2015-06-01 22:41:41,384 [DEBUG] ecm.plugins.accounting.tasks.contracts - Writing contracts to DB...
2015-06-01 22:41:41,384 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 old contracts removed.
2015-06-01 22:41:41,385 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 new contracts added.
2015-06-01 22:41:41,385 [DEBUG] ecm.plugins.accounting.tasks.contracts - Writing contract items to DB...
2015-06-01 22:41:41,385 [INFO ] ecm.plugins.accounting.tasks.contracts - 0 new contract items added.
[01/Jun/2015 22:41:42] "GET /scheduler/tasks/data/?sEcho=3&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191331708 HTTP/1.1" 200 3534
[01/Jun/2015 22:41:47] "GET /scheduler/tasks/data/?sEcho=4&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191336712 HTTP/1.1" 200 3534
[01/Jun/2015 22:41:52] "GET /scheduler/tasks/data/?sEcho=5&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191341717 HTTP/1.1" 200 3534
[01/Jun/2015 22:41:57] "GET /scheduler/tasks/data/?sEcho=6&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191346720 HTTP/1.1" 200 3534
[01/Jun/2015 22:42:02] "GET /scheduler/tasks/data/?sEcho=7&iColumns=8&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=false&sSearch_1=&bRegex_1=false&bSearchable_1=false&sSearch_2=&bRegex_2=false&bSearchable_2=false&sSearch_3=&bRegex_3=false&bSearchable_3=false&sSearch_4=&bRegex_4=false&bSearchable_4=false&sSearch_5=&bRegex_5=false&bSearchable_5=false&sSearch_6=&bRegex_6=false&bSearchable_6=false&sSearch_7=&bRegex_7=false&bSearchable_7=false&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&_=1433191351723 HTTP/1.1" 200 3534
[01/Jun/2015 22:42:06] "GET /accounting/ HTTP/1.1" 200 10317
[01/Jun/2015 22:42:06] "GET /static/accounting/css/classes.css HTTP/1.1" 200 491
[01/Jun/2015 22:42:06] "GET /static/ecm/img/datatables/sort_asc.png HTTP/1.1" 200 2907
[01/Jun/2015 22:42:06] "GET /static/ecm/img/datatables/sort_both.png HTTP/1.1" 200 305
[01/Jun/2015 22:42:06] "GET /accounting/wallets/data/?sEcho=1&iColumns=2&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=true&bSortable_1=true&_=1433191355297 HTTP/1.1" 200 1382
[01/Jun/2015 22:42:06] "GET /static/accounting/img/wallet.png HTTP/1.1" 200 836
[01/Jun/2015 22:42:08] "GET /accounting/contracts/ HTTP/1.1" 200 15035
[01/Jun/2015 22:42:08] "GET /static/hr/css/classes.css HTTP/1.1" 200 1022
[01/Jun/2015 22:42:08] "GET /static/ecm/img/glyphicons-halflings.png HTTP/1.1" 200 13826
[01/Jun/2015 22:42:08] "GET /accounting/contracts/data/?sEcho=1&iColumns=12&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&bSortable_8=false&bSortable_9=false&bSortable_10=false&bSortable_11=false&type=0&status=0 HTTP/1.1" 200 8694
[01/Jun/2015 22:42:08] "GET /static/accounting/img/itemexchange.png HTTP/1.1" 200 2229
[01/Jun/2015 22:42:08] "GET /static/accounting/img/courier.png HTTP/1.1" 200 2218
[01/Jun/2015 22:42:12] "GET /accounting/contracts/data/?sEcho=2&iColumns=12&sColumns=&iDisplayStart=0&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&bSortable_8=false&bSortable_9=false&bSortable_10=false&bSortable_11=false&type=0&status=1 HTTP/1.1" 200 8650
[01/Jun/2015 22:42:16] "GET /accounting/contracts/data/?sEcho=3&iColumns=12&sColumns=&iDisplayStart=25&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&bSortable_8=false&bSortable_9=false&bSortable_10=false&bSortable_11=false&type=0&status=1 HTTP/1.1" 200 8613
[01/Jun/2015 22:42:17] "GET /accounting/contracts/data/?sEcho=4&iColumns=12&sColumns=&iDisplayStart=50&iDisplayLength=25&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&bSortable_0=false&bSortable_1=false&bSortable_2=false&bSortable_3=false&bSortable_4=false&bSortable_5=false&bSortable_6=false&bSortable_7=false&bSortable_8=false&bSortable_9=false&bSortable_10=false&bSortable_11=false&type=0&status=1 HTTP/1.1" 200 5876

**Comment by Dharr-Guartonzec** [comment]
I did restart the server, so nothing is blocking that file now. still error.log 0 byte and apapche still reports it has no access to that file. :/

**Comment by ggrog** [comment]
Sorry for the runaround.

Well, looks like this is totally an oversight - ECM doesn't look for changes in contract state.  They stick around until they get removed from the old contract cache, whenever that is!

**Comment by Dharr-Guartonzec** [comment]
thx, for looking into this :) i'm happy to debug any further if required.

**Comment by Dharr-Guartonzec** [comment]
Will there be any change on this behaviour? So that contract state gets updated?

**Comment by ggrog** [comment]
Yes, I plan to do this.  I'm back from my summer break now.

**Comment by ggrog** [comment]
@Dharr-Guartonzec this is ready to test now. `pip install git+https://github.com/evecm/ecm --force-reinstall --no-deps`

**Comment by Dharr-Guartonzec** [comment]
Awesome, i will update right now.

**Comment by Dharr-Guartonzec** [comment]
pip install git+https://github.com/evecm/ecm --force-reinstall --no-deps
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/evecm/ecm
  Cloning https://github.com/evecm/ecm to /tmp/pip-FXjV_i-build
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
  Complete output from command git clone -q https://github.com/evecm/ecm /tmp/pip-FXjV_i-build:

  ----------------------------------------
Command "git clone -q https://github.com/evecm/ecm /tmp/pip-FXjV_i-build" failed with error code 128 in None

**Comment by Dharr-Guartonzec** [comment]
pip install git+https://github.com/evecm/ecm --force-reinstall --no-deps
Collecting git+https://github.com/evecm/ecm
  Cloning https://github.com/evecm/ecm to /tmp/pip-RTz1Yn-build
  Requirement already satisfied (use --upgrade to upgrade): ecm==2.2.4.1 from git+https://github.com/evecm/ecm in /usr/lib/python2.7/site-packages

?!?

**Comment by ggrog** [comment]
`pip install git+https://github.com/evecm/ecm --upgrade --no-deps` ?  (You'd think --force-reinstall would, you know, **force** the installation.)

**Comment by Dharr-Guartonzec** [comment]
screw my last comment i double executed the upgrade somehow. :)

**Comment by Dharr-Guartonzec** [comment]
Okay, i have let someone setup some new contracts for us that we then can accept. Currently ECM shows all the old contracts, that outdated or got removed by the issuer, still as outstanding contracts.

To have a clear state to debug with, i will flush the contracts table and i will test from there.

**Comment by Dharr-Guartonzec** [comment]
OK, after a fresh poll...  i'm now having only completed and some deleted contracts in ECM. I will report back how ECM will handle updates on the contract status as soon as i got some new ones.

**Comment by ggrog** [comment]
@Dharr-Guartonzec Any luck?

**Comment by Dharr-Guartonzec** [comment]
works like a charm, thank you very much. i think we can close this.
