### ISSUE TITLE
Since Carnyx Patch reoccuring Django Errors

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#22]
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 90, in update
    titleDiffs = storeTitles(oldTitles, newTitles, currentTime)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 207, in storeTitles
    d.save()

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)

  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)

Warning: Field 'id' doesn't have a default value

Request repr() unavailable.

**Comment by Dharr-Guartonzec** [comment]
And the other error:

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)

  File "/usr/lib/python2.7/site-packages/ecm/plugins/accounting/tasks/contracts.py", line 52, in update
    process_contracts(contractsApi.contractList, api_conn)

  File "/usr/lib/python2.7/site-packages/ecm/plugins/accounting/tasks/contracts.py", line 113, in process_contracts
    write_contracts(added_contracts, removed_contracts)

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/ecm/plugins/accounting/tasks/contracts.py", line 128, in write_contracts
    contract.save()

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)

  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)

Warning: Incorrect string value: '\xE2\x99\xA3 ex...' for column 'title' at row 1


Request repr() unavailable.

**Comment by Dharr-Guartonzec** [comment]
I re-checked when the issues started, and it was last Saturday, 6th June. So probably doesn't have to do anything with the patch.

**Comment by ggrog** [comment]
First error is an issue I've seen before with titles and I haven't been able to figure it out.  Have you changed anything ingame around the same time with a member's titles, or your titles names or something?

The second is an issue on your end with your database not storing characters in UTF8 properly.  This may help: http://stackoverflow.com/questions/1168036/how-to-fix-incorrect-string-value-errors

**Comment by Dharr-Guartonzec** [comment]
I'm now on current build and Galentea update. The only issue which is left is that Assets are not getting updated. I even deleted assets table and assets diff table. Nothing seems to be execute. I get no error message displayed, wehter outside of ecm or via the django interface. Nothing is logged in ecm.log or into error.log. Also no mail about errors is send. it is hard to debug.

Any idea?

**Comment by Dharr-Guartonzec** [comment]
Took a while for the error mails, here it is:

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)

  File "/usr/lib/python2.7/site-packages/ecm/plugins/assets/tasks/assets.py", line 103, in update
    write_results(new_items, old_items, assets_to_locate, currentTime)

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/ecm/plugins/assets/tasks/assets.py", line 121, in write_results
    update_assets_names()

  File "/usr/lib/python2.7/site-packages/ecm/plugins/assets/tasks/assets.py", line 487, in update_assets_names
    Asset.objects.filter(itemID=itemID).update(name=itemName)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 581, in update
    rows = query.get_compiler(self.db).execute_sql(None)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1020, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)

Warning: Incorrect string value: '\xE2\x99\xA3 Wh...' for column 'name' at row 1


Request repr() unavailable.

**Comment by ggrog** [comment]
Same issue as before, your DB doesn't support UTF-8.  See my first comment in this thread.  Here's another link that may help.
http://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django

**Comment by Dharr-Guartonzec** [comment]
I used the listed script on stackoverflow.com and managed to get rid of this error. tho the script was not able to change the charset of all tables/row. No clue. But my error is fixed now. 

We fixed the error now but that does not give us an idea why that happened...

**Comment by ggrog** [comment]
Glad to hear it's fixed!
