### ISSUE TITLE
Titles and Member tasks issues

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#28]
![ecm-tasks-errors](https://cloud.githubusercontent.com/assets/11791747/9682177/7a88db10-5304-11e5-9375-72591c182f2c.png)

# tail -f ecm.log
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 84, in update
    newTitles.update(parseOneMemberTitles(member, my_corp))
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 122, in parseOneMemberTitles
    title = Title.objects.get(corp=my_corp, titleID=t.titleID)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: Title matching query does not exist.
2015-09-04 12:05:22,771 [INFO ] ecm.apps.hr.tasks.titles - fetching /corp/Titles.xml.aspx...
2015-09-04 12:05:22,941 [INFO ] ecm.apps.hr.tasks.titles - Title "x" does not exist. Creating...
2015-09-04 12:05:22,944 [INFO ] ecm.apps.hr.tasks.titles - Changing group name "Directors" to "x"...
2015-09-04 12:05:22,951 [INFO ] ecm.apps.hr.tasks.titles - Title "x" does not exist. Creating...
2015-09-04 12:05:22,953 [INFO ] ecm.apps.hr.tasks.titles - Changing group name "Members" to "x"...
2015-09-04 12:05:22,968 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/titles.py", line 68, in update
    newList.extend(parse_one_title(title, my_corp))
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/titles.py", line 131, in parse_one_title
    group.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 626, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 605, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1020, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry 'x' for key 'name'")

**Comment by Dharr-Guartonzec** [comment]
Got sorted. 

IntegrityError: (1062, "Duplicate entry 'x' for key 'name'")

There was several unused titles slots named same --> x

After renaming them all different tasks and updates have been working flawlessly.
