### ISSUE TITLE
update_all_character_associations and update_all_users_accesses errors

### ISSUE THREAD

**Issue by Attoy** [evecm/ecm#30]
Lately we are unable to run those two scheduled tasks and the log just file this error:

2015-09-04 14:45:01,728 [ERROR] ecm.apps.scheduler.models - 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/users.py", line 138, in update_all_users_accesses
    raise RuntimeWarning("Last character associations update failed. "
RuntimeWarning: Last character associations update failed. Skipping user access update.

Any help to fix this issue pls?

**Comment by ggrog** [comment]
User access won't update until there's a successful update character associations.  Manually run update_all_character_associations first from the scheduled task page, then run update_all_users_accesses.   This happens every so often when there's an API error.  If you still get an error with update_all_character_associations please post that error.

**Comment by ggrog** [comment]
PS: The update_all_users_accesses task runs every two hours, so one failed update_all_character_associations task will throw 24/2 = 12 errors.

**Comment by Attoy** [comment]
I ran update_all_character_associations from the scheduled task page , it gives me red ERROR on the scheduled task page and this is the only error in the log files:

2015-09-03 18:50:06,644 [WARNING] ecm.apps.hr.tasks.users - 403 - Forbidden (user: '********' keyID: *******)
2015-09-03 18:50:09,217 [ERROR] ecm.apps.scheduler.models - 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/users.py", line 42, in update_all_character_associations
    update_character_associations(user)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/users.py", line 97, in update_character_associations
    alert_user_for_invalid_apis(user, invalid_api_keys)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/common/auth.py", line 82, in alert_user_for_invalid_apis
    msg.send()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/message.py", line 255, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 88, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 49, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
    return socket.create_connection((port, host), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused

(covered username and KeyId with asterisks)

It looks like ECM tries to send an email due to invalid API but it can't. Is this the reason of the failed task?

**Comment by Attoy** [comment]
Yes, it was the mail server. ECM tries to send an email warning to an user about faulty API and it hangs due to misconfiguration of the mail server.

**Comment by ggrog** [comment]
Yes, it sure looked like the mail server.  Glad you got it sorted!
