### ISSUE TITLE
Members Update fails again

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evecm/ecm#32]
One day without errors, suddenly an old issue returned:

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 90, in update
    titleDiffs = storeTitles(oldTitles, newTitles, currentTime)

  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 207, in storeTitles
    d.save()

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)

  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()

  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)

Warning: Field 'id' doesn't have a default value

Request repr() unavailable.

What else can be the error here? Setting the DB to UTF-8 charset did not solve all the issues.

The last thing that changed was a new member joining our corp yesterday... Before that all worked fine.

**Comment by Dharr-Guartonzec** [comment]
Okay, looks like this is same issue as reported in issue #14 so i close this here

**Comment by ggrog** [comment]
Thanks for the report, the new member joining corp is a good hint.
