### ISSUE TITLE
Wallet Journal Not Loading

### ISSUE THREAD

**Issue by lexcomman** [evecm/ecm#46]
When going to the wallet journal I'm not able to modify the date and time. I get a constant processing. Also when I try and select any more than 50 lines per page I get a constant processing.

**Comment by lexcomman** [comment]
2016-04-01 01:19:19,872 [ERROR] django.request - Internal Server Error: /accounting/journal/data/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/views/decorators.py", line 104, in _wrapped_view
    return view_function(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/plugins/accounting/views/journal.py", line 175, in journal_data
    rat_list.append('%s x%s' % (Type.objects.get(typeID=rat_id).typeName, rat_count))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: Type matching query does not exist.

**Comment by ggrog** [comment]
Typically because this is because the data load failed.  Try reloading the static DB from the files available at www.ggrog.com instead of using Fuzzworks.

**Comment by lexcomman** [comment]
Looks like that site is currently down, not able to load the most recent database.

**Comment by swstim** [comment]
ggrog.com is back up.
