### ISSUE TITLE
Incorrect string value: '\\xE2\\x94\\x80\\xE2\\x94\\x80...' for column 'description'

### ISSUE THREAD

**Issue by markus-lassfolk** [evecm/ecm#47]
I'm getting this error when processing API keys; 
I suspect it's because the corp has some ascii in the corp description; 
─────▄───▄
─▄█▄─█▀█▀█─▄█▄
▀▀████▄█▄████▀▀
─────▀█▀█▀

2016-08-08 15:16:37,193 [INFO ] ecm.apps.corp.utils - Adding new Corporation: 7 White Horses
2016-08-08 15:16:37,195 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/home/username/.local/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(*_args)
  File "/home/username/.local/lib/python2.7/site-packages/ecm/apps/hr/tasks/users.py", line 42, in update_all_character_associations
    update_character_associations(user)
  File "/home/username/.local/lib/python2.7/site-packages/ecm/apps/hr/tasks/users.py", line 75, in update_character_associations
    corp = get_corp(char.corporationID)
  File "/home/username/.local/lib/python2.7/site-packages/ecm/apps/corp/utils.py", line 53, in get_corp
    corp.save()
  File "/home/username/.local/lib/python2.7/site-packages/ecm/apps/corp/models.py", line 190, in save
    models.Model.save(self, force_insert=force_insert, force_update=force_update, using=using)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, *_kwargs)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/home/username/.local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 128, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/username/.local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
DatabaseError: (1366, "Incorrect string value: '\xE2\x94\x80\xE2\x94\x80...' for column 'description' at row 1")
ERROR in task "ecm.apps.hr.tasks.users.update_all_character_associations"

**Comment by ggrog** [comment]
Is this is a new instance?  This is probably a database setup issue, make sure your MySQL tables support utf8.

**Comment by markus-lassfolk** [comment]
Wow, you are so right. After changing from the default latin_blabla to UTF8_generic_ci it's all working as expected.  :+1:  Thanks a lot for not just the ultrafast answer but also for all the job you are doing with ECM!
