### ISSUE TITLE
Unable to update database

### ISSUE THREAD

**Issue by lexcomman** [evecm/ecm#49]
I am unable to update the database. I am receiving the errors below when trying to use either the fuzzworks or ggrog.com databases. I saw a similar issue that was resolved by only running django 1.5.7, which I am. I have fully uninstalled ECM and reinstalled using the pip ecm, and also pulling straight from the repository live data. Neither seem to resolve this one issue. Any help would be appreciated.

Traceback (most recent call last):
  File "/usr/local/bin/ecm-admin", line 11, in <module>
    load_entry_point('ecm==2.2.5', 'console_scripts', 'ecm-admin')()
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cli.py", line 50, in main
    command.run(command, global_options, options, args)
  File "/usr/local/lib/python2.7/dist-packages/ecm/lib/subcommand.py", line 50, in run
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cmd/load.py", line 118, in run
    load_dump_file(instance_dir, savedir, tempdir, dumppath, db_engine, db_password)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cmd/load.py", line 194, in load_dump_file
    pipe_to_dbshell(dump_file, instance_dir, password=db_password)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/util.py", line 165, in pipe_to_dbshell
    proc.stdin.write(sql)
IOError: [Errno 32] Broken pipe

**Comment by lexcomman** [comment]
Here is the fuzworks fail. 

Traceback (most recent call last):
  File "/usr/local/bin/ecm-admin", line 11, in <module>
    load_entry_point('ecm==2.2.5', 'console_scripts', 'ecm-admin')()
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cli.py", line 50, in main
    command.run(command, global_options, options, args)
  File "/usr/local/lib/python2.7/dist-packages/ecm/lib/subcommand.py", line 50, in run
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cmd/load.py", line 114, in run
    load_dump_file(instance_dir, savedir, tempdir, os.path.join(dumppath, table) + FUZZWORK_URL_SUFFIX, db_engine, db_password)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/cmd/load.py", line 194, in load_dump_file
    pipe_to_dbshell(dump_file, instance_dir, password=db_password)
  File "/usr/local/lib/python2.7/dist-packages/ecm/admin/util.py", line 165, in pipe_to_dbshell
    proc.stdin.write(sql)
IOError: [Errno 32] Broken pipe

**Comment by lexcomman** [comment]
Any help would appreciated. Still having this issue. I've tried reinstalling from a new system install, and still have the same issue.
