### ISSUE TITLE
Dump Import Error: Broken pipe

### ISSUE THREAD

**Issue by bastrian** [evecm/ecm#7]
After executing the following command under Ubuntu Server:
ecm-admin load /var/www/corp http://ggrog.com/hyperion.my.sql.bz2
it gets the following error:

Traceback (most recent call last):
  File "/usr/local/bin/ecm-admin", line 9, in <module>
    load_entry_point('ecm==2.2.1.dev', 'console_scripts', 'ecm-admin')()
  File "/usr/local/lib/python2.7/dist-packages/ecm-2.2.1.dev-py2.7.egg/ecm/admin/cli.py", line 50, in main
    command.run(command, global_options, options, args)
  File "/usr/local/lib/python2.7/dist-packages/ecm-2.2.1.dev-py2.7.egg/ecm/lib/subcommand.py", line 50, in run
    return self.callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm-2.2.1.dev-py2.7.egg/ecm/admin/cmd/load.py", line 129, in run
    pipe_to_dbshell(dump_file, instance_dir, password=db_password)
  File "/usr/local/lib/python2.7/dist-packages/ecm-2.2.1.dev-py2.7.egg/ecm/admin/util.py", line 165, in pipe_to_dbshell
    proc.stdin.write(sql)
IOError: [Errno 32] Broken pipe

I guess that mysql runs out of buffer or the connection does not get closed.

**Comment by ggrog** [comment]
Using django==1.5.7 fixes this, see #8
